#!/bin/bash

# Colors
Color_Off='\033[0m'       # Text Reset
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m' 

echo -e "$Green=== INCREASED WEAPON RANGES GENERATOR ===$Color_Off"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "We're currently in: $SCRIPT_DIR"

read -p "Reset to default before applying factor? [Y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo "Removing previously generated files..."
	rm -rf "$SCRIPT_DIR/assets" "$SCRIPT_DIR/extensions"

	echo "Reseting to default values..."
	rsync -a "$SCRIPT_DIR/_default/"* "$SCRIPT_DIR/"
fi

echo "Asking range factor..."
while :; do
	read -ep 'Enter range factor 1 to 9 (will be modulated by weapon type and current values): ' FACTOR 
    	[[ $FACTOR =~ ^[[:digit:]]+$ ]] || continue
		[[ $FACTOR -lt 10 && $FACTOR -gt 0 ]] || continue
    	break
done

echo "Listing Vanilla files..."
while IFS=  read -r -d $'\0'; do
    FINDFILES+=("$REPLY")
done < <(find "$SCRIPT_DIR/assets" "$SCRIPT_DIR/extensions" -type f -name "*.xml"  -print0)

TOTALFILES=${#FINDFILES[@]}
echo -e "Number of files to modify : $TOTALFILES"

read -p "Proceed?  [Y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]
then
	exit 0
fi

echo -e "Applying factor $factor...\n\n"
COUNT=0
echo -e "Done : $COUNT/$TOTALFILES"
# loop over files
for FILE in "${FINDFILES[@]}"
do
	#BEGIN LOGICAL CALCULATION ON A SINGLE FILE

	MACRO=$(grep -oP '<macro name="\K[^"]+' "$FILE")
	BULLET_LINE=$(grep '<bullet ' "$FILE")

	if [[ -z "$MACRO" || -z "$BULLET_LINE" ]]; then
		echo ""
		echo -e "$Red❌\tNo valid macro in file: $FILE$Color_Off"
		continue
	fi

	# Weapon type based on macro name
	TYPE=""
	[[ $MACRO =~ (gatling|plasma|laser|charge|cannon|shotgun|ion|flak|sticky|arc|swarm) ]] && TYPE="ballistic"
	[[ $MACRO =~ railgun ]] && TYPE="railgun"
	[[ $MACRO =~ (beam|mining|burst|missile|torpedo|nova|bio) ]] && TYPE="range_based"
	[[ $MACRO =~ engine ]] && TYPE="engine"

	#DEBUG
	# echo "Captured macro : $MACRO"
	# echo "Identified type : $TYPE"
	# echo "Bullet line : $BULLET_LINE"
	#END DEBUG

	MODIFIED_ATTRS=""

	# Getting value
	get_attr() {
		echo "$BULLET_LINE" | grep -oP "$1=\"\K[^\"]+"
	}

	# Setting value
	set_attr() {
		awk "BEGIN { printf \"%.6f\", $1 }"
	}

	if [[ $TYPE == "ballistic" ]]; then
		SPEED=$(get_attr "speed")
		ANGLE=$(get_attr "angle")
		[[ $SPEED ]] && MODIFIED_ATTRS+=" speed=\"$(set_attr "$SPEED * $FACTOR")\""
		[[ $ANGLE ]] && MODIFIED_ATTRS+=" angle=\"$(set_attr "$ANGLE / $FACTOR")\""

	elif [[ $TYPE == "railgun" ]]; then
		SPEED=$(get_attr "speed")
		[[ $SPEED ]] && MODIFIED_ATTRS+=" speed=\"$(set_attr "$SPEED * $FACTOR")\""

	elif [[ $TYPE == "range_based" ]]; then
		RANGE=$(get_attr "range")
		LIFE=$(get_attr "lifetime")
		[[ $RANGE ]] && MODIFIED_ATTRS+=" range=\"$(set_attr "$RANGE * $FACTOR")\""
		[[ $LIFE ]] && MODIFIED_ATTRS+=" lifetime=\"$(set_attr "$LIFE * $FACTOR")\""

	elif [[ $TYPE == "engine" ]]; then
		THRUST=$(grep -oP 'forward="\K[0-9.]+' "$FILE")
		[[ $THRUST ]] && MODIFIED_ATTRS+=" forward=\"$(set_attr "$THRUST * $FACTOR")\""
	fi

	#DEBUG
	#echo "Modified attributes : $MODIFIED_ATTRS"
	#END DEBUG

	# Génération du diff uniquement si on a quelque chose à modifier
	if [[ -n "$MODIFIED_ATTRS" ]]; then
	  {
		echo '<?xml version="1.0" encoding="utf-8"?>'
		echo '<!-- GENERATED BY "Increased Weapon Ranges" Mod by Laryakan, $(date '+%Y-%m-%d') -->'
		echo '<diff>'
		echo "  <replace sel=\"/macros/macro[@name='$MACRO']/properties/bullet\">"
		echo "    <bullet$MODIFIED_ATTRS />"
		echo "  </replace>"
		echo '</diff>'
	  } > "$FILE"
		#echo -e "$Green✔\tDiff generated in $FILE$Color_Off"
		COUNT=$((COUNT+1))
		echo -ne "\rDone : $COUNT/$TOTALFILES"
	else
		echo ""
		echo -e "$Yellow⚠\tCan't change anything in $FILE$Color_Off"
	fi
	
	#DEBUG
	#exit 0
	#END DEBUG

	# END LOGICAL CALCULATION
done

echo -e "\n"



